---
title: "Untitled"
output: html_document
date: "2025-03-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
library(dplyr)
```



```{r}
base <- read.csv("securite.csv",sep=";", header=TRUE, stringsAsFactors=FALSE, check.names=FALSE)

```

```{r}
library(tibble)

# Générer une base fictive
set.seed(123)
fake_data <- tibble(
  `Age du chef de ménage` = sample(18:80, 50, replace = TRUE),
  `salaire du chef de ménage` = sample(50000:500000, 50, replace = TRUE),
  `Dépenses mensuelles du ménage` = sample(30000:600000, 50, replace = TRUE),
  `Nombre de personnes du ménage` = sample(1:15, 50, replace = TRUE)
)

# Sauvegarder la base fictive dans un fichier CSV
write.csv(fake_data, "securite_fictive.csv", row.names = FALSE)

```

```{r}
# Générer une base fictive
set.seed(123)
fake_data <- tibble(
  Age = sample(18:80, 50, replace = TRUE),
  salaire = sample(50000:500000, 50, replace = TRUE),
  depenses = sample(30000:600000, 50, replace = TRUE),
  Nombre = sample(1:15, 50, replace = TRUE)
)

# Sauvegarder la base fictive dans un fichier CSV
write.csv(fake_data, "securite_fictive.csv", row.names = FALSE)
```



