#nom du worklow
name : Importations_données

on :
  workflow_dispatch:
#quand 
jobs: 
  importation:
     permissions:
       contents: write
       pages:write
    runs-on: ubunto-latest
    
    steps:
     -name:check out repository
      uses: actions/checkout@v3
     -name: install R
     uses: r-lib/actions/setup-r@v2
     with:
       packages:
         any::tidyverse
         any::robotoolbox
    -name : importation données 
    run: Rdcript -e 'source("import_data.R")'
    env:
      env:
          MY_TOKEN: ${{ secrets.MY_TOKEN_GHA }}
          MY_UID: ${{ secrets.MY_UID_GHA }}
          
      - name: commit results
        run: |
          git config --local user.email "somaben791@gmail.com"
          git config --local user.name "Ben10-som"
          git add df.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
        






