jobs:
  Importation_kobo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libfontconfig1-dev

    - name: Install R packages
      run: |
        Rscript -e "install.packages('curl')"
        Rscript -e "install.packages('systemfonts')"
    
    - name: Run R script
      run: Rscript your_script.R
