name: Importation_kobo

on:
  workflow_dispatch:

jobs:
  importation:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("tidyverse", "robotoolbox", "shiny", "DT", "ggplot2", "dplyr", "tibble", "gridExtra"), repos="http://cran.rstudio.com")'

      - name: Importation des données
        run: Rscript -e 'source("importation.R")'
        env:
          MY_TOKEN: ${{ secrets.my_token }}
          MY_UID: ${{ secrets.my_uid }}

      - name: Commit results
        run: |
          git config --local user.email "somaben791@gmail.com"
          git config --local user.name "Ben10-som"
          git add df.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
